### ISSUE TITLE
fatal error: email-client/email.h: No such file or directory

### ISSUE THREAD

**Issue by junecat** [imnetcat/email-client#54]
Здравствуйте.

Спасибо за ваш проект. Очень удобно, что он не тащит за собой монстров типа boost.

Есть небольшая проблема, в how to start указано подключение заголовочного файла, которого нет в проекте.

Спасибо, если сможете это поправить.

**Comment by junecat** [comment]
Круто! спасибо

**Comment by imnetcat** [comment]
Спасибо что написали
Исправил
Это ещё не релизная версия, там много лишнего, отладочного кода
Заявленый функционал уже реализован, но могут быть баги. Но для относительно простых целей всё уже должно работать
Вы можете попробовать убрать тесты и отладочный код для ещё меньшего размера
P.S.: Be free to create new issues
